2020-04-21 09:51:55,635 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 09:57:15,660 - 销售品名:test /当前任务库存: 1
2020-04-21 09:57:27,691 - Working! waitting:32 min
2020-04-21 09:57:39,451 - Not Found: /favicon.ico
2020-04-21 10:02:35,658 - no mission! Please add!
2020-04-21 10:07:55,691 - no mission! Please add!
2020-04-21 10:12:54,732 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:14:44,764 - no mission! Please add!
2020-04-21 10:15:13,301 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:18:03,340 - no mission! Please add!
2020-04-21 10:20:53,362 - no mission! Please add!
2020-04-21 10:22:20,376 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:23:50,396 - no mission! Please add!
2020-04-21 10:24:19,986 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:25:02,798 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:28:02,832 - no mission! Please add!
2020-04-21 10:29:04,580 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:30:19,862 - Internal Server Error: /items/create/
Traceback (most recent call last):
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\14623\Documents\GitHub\xiangyan\items\views.py", line 106, in itemCreate
    return render(request, 'itemCreate.html', context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\urls\resolvers.py", line 634, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'insert' not found. 'insert' is not a valid view function or pattern name.
2020-04-21 10:30:20,221 - Not Found: /favicon.ico
2020-04-21 10:31:04,606 - no mission! Please add!
2020-04-21 10:32:00,870 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:32:07,777 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:32:13,160 - Internal Server Error: /items/create/
Traceback (most recent call last):
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\14623\Documents\GitHub\xiangyan\items\views.py", line 106, in itemCreate
    return render(request, 'itemCreate.html', context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\urls\resolvers.py", line 634, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'insert' not found. 'insert' is not a valid view function or pattern name.
2020-04-21 10:33:27,819 - no mission! Please add!
2020-04-21 10:34:34,757 - Internal Server Error: /items/create/
Traceback (most recent call last):
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\14623\Documents\GitHub\xiangyan\items\views.py", line 106, in itemCreate
    return render(request, 'itemCreate.html', context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\urls\resolvers.py", line 634, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'insert' not found. 'insert' is not a valid view function or pattern name.
2020-04-21 10:34:47,837 - no mission! Please add!
2020-04-21 10:36:07,823 - no mission! Please add!
2020-04-21 10:36:30,973 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:36:34,613 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:37:00,056 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:37:00,236 - Internal Server Error: /items/create/
Traceback (most recent call last):
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\14623\Documents\GitHub\xiangyan\items\views.py", line 106, in itemCreate
    return render(request, 'itemCreate.html', context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\urls\resolvers.py", line 634, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'insert' not found. 'insert' is not a valid view function or pattern name.
2020-04-21 10:37:11,187 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:39:21,204 - no mission! Please add!
2020-04-21 10:41:31,244 - no mission! Please add!
2020-04-21 10:43:41,252 - no mission! Please add!
2020-04-21 10:45:51,224 - no mission! Please add!
2020-04-21 10:48:01,233 - no mission! Please add!
2020-04-21 10:50:11,229 - no mission! Please add!
2020-04-21 10:52:21,231 - no mission! Please add!
2020-04-21 10:54:31,210 - no mission! Please add!
2020-04-21 10:56:41,244 - no mission! Please add!
2020-04-21 10:56:55,159 - Internal Server Error: /items/file/upload/
Traceback (most recent call last):
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\14623\Documents\GitHub\xiangyan\items\views.py", line 232, in fileUpload
    for chunk in file_obj.chunks():
AttributeError: 'NoneType' object has no attribute 'chunks'
2020-04-21 10:57:22,386 - Internal Server Error: /items/file/upload/
Traceback (most recent call last):
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\14623\Documents\GitHub\xiangyan\items\views.py", line 232, in fileUpload
    for chunk in file_obj.chunks():
AttributeError: 'NoneType' object has no attribute 'chunks'
2020-04-21 10:58:13,686 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:59:15,736 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 10:59:27,891 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 11:00:20,354 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 11:00:38,145 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 11:00:48,282 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 11:02:41,426 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 11:03:08,902 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 12:00:03,924 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 12:00:35,546 - 开始导入===>upload/2020-04-21.xlsx
2020-04-21 12:00:36,566 - =====导入完成=====
2020-04-21 12:02:43,943 - no mission! Please add!
2020-04-21 12:05:23,960 - no mission! Please add!
2020-04-21 12:06:56,287 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 12:09:46,311 - no mission! Please add!
2020-04-21 12:11:52,799 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 12:13:26,432 - 开始导入===>upload/2020-04-21.xlsx
2020-04-21 12:13:27,420 - =====导入完成=====
2020-04-21 12:13:27,420 - Internal Server Error: /items/file/upload/
Traceback (most recent call last):
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\14623\Documents\GitHub\xiangyan\env\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\14623\Documents\GitHub\xiangyan\items\views.py", line 252, in fileUpload
    book = xlrd.open_workbook(self.file)
NameError: name 'self' is not defined
2020-04-21 12:13:54,743 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 12:14:01,981 - 开始导入===>upload/2020-04-21.xlsx
2020-04-21 12:14:02,497 - =====导入完成=====
2020-04-21 12:15:28,561 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 12:15:38,466 - 开始导入===>upload/2020-04-21.xlsx
2020-04-21 12:15:39,168 - =====导入完成=====
2020-04-21 12:16:14,096 - 开始导入===>upload/2020-04-21.xlsx
2020-04-21 12:16:14,643 - =====导入完成=====
2020-04-21 12:17:18,577 - no mission! Please add!
2020-04-21 12:19:08,622 - no mission! Please add!
2020-04-21 12:20:58,631 - no mission! Please add!
2020-04-21 12:22:48,606 - no mission! Please add!
2020-04-21 12:24:38,625 - no mission! Please add!
2020-04-21 12:26:28,598 - no mission! Please add!
2020-04-21 12:28:18,607 - no mission! Please add!
2020-04-21 12:30:08,583 - no mission! Please add!
2020-04-21 12:31:58,612 - no mission! Please add!
2020-04-21 12:33:48,598 - no mission! Please add!
2020-04-21 12:35:38,615 - no mission! Please add!
2020-04-21 12:37:28,584 - no mission! Please add!
2020-04-21 12:39:18,631 - no mission! Please add!
2020-04-21 12:41:08,605 - no mission! Please add!
2020-04-21 12:42:58,609 - no mission! Please add!
2020-04-21 12:44:48,592 - no mission! Please add!
2020-04-21 12:46:38,598 - no mission! Please add!
2020-04-21 12:48:28,604 - no mission! Please add!
2020-04-21 12:50:18,612 - no mission! Please add!
2020-04-21 12:51:56,307 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 12:53:26,740 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 12:56:46,761 - no mission! Please add!
2020-04-21 12:56:55,391 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 12:58:01,570 - 开始导入===>upload/2020-04-21.xlsx
2020-04-21 12:58:02,570 - =====导入完成=====
2020-04-21 12:58:43,269 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 12:59:57,553 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:00:06,457 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:00:12,797 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:00:23,819 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:02:55,155 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:04:05,175 - no mission! Please add!
2020-04-21 13:04:16,854 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:05:52,648 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:06:22,233 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:06:46,383 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:10:18,097 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:10:33,123 - 销售品名:好猫(猴王磨砂) /当前任务库存: 11
2020-04-21 13:10:45,138 - Working! waitting:15 min
2020-04-21 13:10:48,145 - 销售品名:好猫(猴王磨砂) /当前任务库存: 10
2020-04-21 13:11:00,161 - Working! waitting:29 min
2020-04-21 13:11:03,157 - 销售品名:好猫(猴王磨砂) /当前任务库存: 9
2020-04-21 13:11:15,173 - Working! waitting:29 min
2020-04-21 13:11:18,164 - 销售品名:好猫(猴王磨砂) /当前任务库存: 8
2020-04-21 13:11:30,181 - Working! waitting:11 min
2020-04-21 13:11:33,153 - 销售品名:好猫(猴王磨砂) /当前任务库存: 7
2020-04-21 13:11:45,173 - Working! waitting:7 min
2020-04-21 13:11:48,152 - 销售品名:好猫(猴王磨砂) /当前任务库存: 6
2020-04-21 13:12:00,176 - Working! waitting:9 min
2020-04-21 13:12:03,174 - 销售品名:好猫(猴王磨砂) /当前任务库存: 5
2020-04-21 13:12:15,195 - Working! waitting:11 min
2020-04-21 13:12:18,159 - 销售品名:好猫(猴王磨砂) /当前任务库存: 4
2020-04-21 13:12:30,183 - Working! waitting:11 min
2020-04-21 13:12:33,170 - 销售品名:好猫(猴王磨砂) /当前任务库存: 3
2020-04-21 13:12:45,185 - Working! waitting:6 min
2020-04-21 13:12:48,146 - 销售品名:好猫(猴王磨砂) /当前任务库存: 2
2020-04-21 13:13:00,161 - Working! waitting:7 min
2020-04-21 13:13:03,148 - 销售品名:好猫(猴王磨砂) /当前任务库存: 1
2020-04-21 13:13:15,163 - Working! waitting:6 min
2020-04-21 13:13:18,131 - no mission! Please add!
2020-04-21 13:13:33,157 - no mission! Please add!
2020-04-21 13:13:48,133 - no mission! Please add!
2020-04-21 13:14:03,156 - no mission! Please add!
2020-04-21 13:14:18,131 - no mission! Please add!
2020-04-21 13:14:33,164 - no mission! Please add!
2020-04-21 13:14:48,150 - no mission! Please add!
2020-04-21 13:15:03,153 - no mission! Please add!
2020-04-21 13:15:18,128 - no mission! Please add!
2020-04-21 13:15:33,143 - no mission! Please add!
2020-04-21 13:15:48,127 - no mission! Please add!
2020-04-21 13:16:03,125 - no mission! Please add!
2020-04-21 13:16:18,131 - no mission! Please add!
2020-04-21 13:16:33,141 - no mission! Please add!
2020-04-21 13:16:48,153 - no mission! Please add!
2020-04-21 13:17:03,142 - no mission! Please add!
2020-04-21 13:17:18,149 - no mission! Please add!
2020-04-21 13:17:33,140 - no mission! Please add!
2020-04-21 13:17:48,136 - no mission! Please add!
2020-04-21 13:18:03,151 - no mission! Please add!
2020-04-21 13:18:18,148 - no mission! Please add!
2020-04-21 13:18:33,159 - no mission! Please add!
2020-04-21 13:18:48,136 - no mission! Please add!
2020-04-21 13:19:03,128 - no mission! Please add!
2020-04-21 13:19:18,144 - no mission! Please add!
2020-04-21 13:19:33,146 - no mission! Please add!
2020-04-21 13:19:48,120 - no mission! Please add!
2020-04-21 13:20:03,144 - no mission! Please add!
2020-04-21 13:20:18,154 - no mission! Please add!
2020-04-21 13:20:33,154 - no mission! Please add!
2020-04-21 13:20:48,149 - no mission! Please add!
2020-04-21 13:20:55,077 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:21:01,091 - no mission! Please add!
2020-04-21 13:21:07,113 - no mission! Please add!
2020-04-21 13:21:12,774 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:21:17,285 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:21:19,397 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:21:23,998 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:21:30,019 - no mission! Please add!
2020-04-21 13:21:36,021 - no mission! Please add!
2020-04-21 13:21:42,046 - no mission! Please add!
2020-04-21 13:21:48,023 - no mission! Please add!
2020-04-21 13:21:54,049 - no mission! Please add!
2020-04-21 13:22:00,057 - no mission! Please add!
2020-04-21 13:22:06,041 - no mission! Please add!
2020-04-21 13:22:12,020 - no mission! Please add!
2020-04-21 13:22:18,051 - no mission! Please add!
2020-04-21 13:22:24,038 - no mission! Please add!
2020-04-21 13:22:30,052 - no mission! Please add!
2020-04-21 13:22:36,034 - no mission! Please add!
2020-04-21 13:22:42,049 - no mission! Please add!
2020-04-21 13:22:48,021 - no mission! Please add!
2020-04-21 13:22:54,056 - 销售品名:云烟(中支金腰带) /当前任务库存: 1
2020-04-21 13:23:00,038 - Execution of job "test_job (trigger: interval[0:00:06], next run at: 2020-04-21 13:22:59 CST)" skipped: maximum number of running instances reached (1)
2020-04-21 13:23:06,020 - Execution of job "test_job (trigger: interval[0:00:06], next run at: 2020-04-21 13:23:05 CST)" skipped: maximum number of running instances reached (1)
2020-04-21 13:23:06,072 - Working! waitting:7 min
2020-04-21 13:23:12,025 - no mission! Please add!
2020-04-21 13:23:18,035 - no mission! Please add!
2020-04-21 13:23:24,033 - no mission! Please add!
2020-04-21 13:23:30,044 - no mission! Please add!
2020-04-21 13:23:36,037 - no mission! Please add!
2020-04-21 13:23:42,050 - no mission! Please add!
2020-04-21 13:23:48,035 - no mission! Please add!
2020-04-21 13:23:56,971 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:23:58,972 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:24:02,096 - Job with id items.views.test_job already in jobstore. I'll refresh it
2020-04-21 13:24:11,109 - no mission! Please add!
2020-04-21 13:24:20,145 - no mission! Please add!
2020-04-21 13:24:29,143 - no mission! Please add!
2020-04-21 13:24:38,132 - no mission! Please add!
2020-04-21 13:24:47,153 - no mission! Please add!
2020-04-21 13:24:56,144 - no mission! Please add!
2020-04-21 13:25:05,136 - no mission! Please add!
2020-04-21 13:25:14,130 - no mission! Please add!
2020-04-21 13:25:23,157 - no mission! Please add!
2020-04-21 13:25:32,151 - no mission! Please add!
2020-04-21 13:25:41,159 - no mission! Please add!
2020-04-21 13:25:50,130 - no mission! Please add!
2020-04-21 13:25:59,140 - no mission! Please add!
2020-04-21 13:26:08,134 - no mission! Please add!
2020-04-21 13:26:17,152 - no mission! Please add!
2020-04-21 13:26:26,129 - no mission! Please add!
2020-04-21 13:26:35,142 - no mission! Please add!
2020-04-21 13:26:44,128 - no mission! Please add!
2020-04-21 13:26:53,160 - no mission! Please add!
2020-04-21 13:27:02,145 - no mission! Please add!
2020-04-21 13:27:11,149 - no mission! Please add!
2020-04-21 13:27:20,132 - no mission! Please add!
2020-04-21 13:27:29,127 - no mission! Please add!
2020-04-21 13:27:38,129 - no mission! Please add!
2020-04-21 13:27:47,144 - no mission! Please add!
2020-04-21 13:27:56,128 - no mission! Please add!
2020-04-21 13:28:05,144 - no mission! Please add!
2020-04-21 13:28:14,119 - no mission! Please add!
2020-04-21 13:28:23,131 - no mission! Please add!
2020-04-21 13:28:32,137 - no mission! Please add!
2020-04-21 13:28:41,147 - no mission! Please add!
2020-04-21 13:28:50,120 - no mission! Please add!
2020-04-21 13:28:59,130 - no mission! Please add!
2020-04-21 13:29:08,124 - no mission! Please add!
2020-04-21 13:29:17,148 - 销售品名:好猫(猴王磨砂) /当前任务库存: 1
2020-04-21 13:29:26,122 - Execution of job "test_job (trigger: interval[0:00:09], next run at: 2020-04-21 13:29:26 CST)" skipped: maximum number of running instances reached (1)
2020-04-21 13:29:29,164 - Working! waitting:10 min
2020-04-21 13:29:35,114 - no mission! Please add!
2020-04-21 13:29:44,130 - no mission! Please add!
2020-04-21 13:29:53,133 - no mission! Please add!
2020-04-21 13:30:02,139 - no mission! Please add!
2020-04-21 13:30:11,133 - no mission! Please add!
2020-04-21 13:30:20,136 - no mission! Please add!
2020-04-21 13:30:29,132 - no mission! Please add!
2020-04-21 13:30:38,132 - no mission! Please add!
2020-04-21 13:30:47,135 - no mission! Please add!
2020-04-21 13:30:56,132 - no mission! Please add!
2020-04-21 13:31:05,127 - no mission! Please add!
2020-04-21 13:31:14,146 - no mission! Please add!
